import React from 'react';
import ReactDOM from 'react-dom/client';
import tailwindCssUrl from '@/assets/tailwind.css?url';

import { Home } from '@/components/Home';
import { ThemeProvider } from '@/hooks/useTheme';
import { ExplorerProvider } from '@/contexts/ExplorerContext';

export default defineUnlistedScript(() => {
  // Bail at runtime if not on a file:// URL or if this isn't a directory.
  if (window.location.protocol !== 'file:') return;
  if (!looksLikeDirectory()) return;

  // Avoid double-mounting.
  if (document.getElementById('files-explorer-host')) return;

  mountShadowRoot();
});

function mountShadowRoot() {
  // Hide the native Chrome directory listing so we don't show two views at
  // once. The dismiss button restores it.
  const nativeElements: Element[] = [];
  for (const child of Array.from(document.body.children)) {
    if (child.id === 'files-explorer-host') continue;
    if (child instanceof HTMLElement) {
      nativeElements.push(child);
      child.dataset['filesExplorerHidden'] = '1';
      child.style.display = 'none';
    }
  }

  const host = document.createElement('div');
  host.id = 'files-explorer-host';
  host.style.cssText =
    'all: initial; contain: layout style; display: block; position: fixed; inset: 0; z-index: 2147483647; background: var(--background, #fff);';
  document.body.appendChild(host);

  const shadow = host.attachShadow({ mode: 'open' });

  // Reset body so the host page CSS doesn't bleed into the shadow root.
  const reset = document.createElement('style');
  reset.textContent = ':host { all: initial; } :host > * { all: revert; }';
  shadow.appendChild(reset);

  // Load the Tailwind CSS bundle generated by Vite. Using ?url (not ?inline)
  // keeps PostCSS/Tailwind processing intact so utility classes get emitted.
  const linkEl = document.createElement('link');
  linkEl.rel = 'stylesheet';
  linkEl.href = chrome.runtime.getURL(
    (tailwindCssUrl as unknown as string).replace(/^\/+/, ''),
  );
  shadow.appendChild(linkEl);

  // Restore native listing when the host element is removed.
  const observer = new MutationObserver(() => {
    if (!document.getElementById('files-explorer-host')) {
      for (const el of nativeElements) {
        if (el instanceof HTMLElement) {
          el.style.display = '';
          delete el.dataset['filesExplorerHidden'];
        }
      }
      observer.disconnect();
    }
  });
  observer.observe(document.body, { childList: true });

  const container = document.createElement('div');
  container.className = 'files-explorer-root';
  container.style.cssText = 'width: 100%; height: 100vh;';
  shadow.appendChild(container);

  const root = ReactDOM.createRoot(container);
  root.render(
    React.createElement(
      React.StrictMode,
      null,
      React.createElement(
        ThemeProvider,
        null,
        React.createElement(
          ExplorerProvider,
          null,
          React.createElement(Home),
        ),
      ),
    ),
  );
}

function looksLikeDirectory(): boolean {
  if (typeof document === 'undefined') return false;
  if (document.querySelector('table')) return true;
  const links = Array.from(document.querySelectorAll('a[href]'));
  let relativeCount = 0;
  for (const a of links) {
    const href = (a as HTMLAnchorElement).getAttribute('href') ?? '';
    if (
      href &&
      !href.startsWith('http://') &&
      !href.startsWith('https://') &&
      !href.startsWith('#')
    ) {
      relativeCount++;
      if (relativeCount >= 3) return true;
    }
  }
  return false;
}
